# Generated by Django 4.2.11 on 2024-05-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
    ]
