# Generated by Django 4.2.11 on 2024-05-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0002_dishes_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
