# Generated by Django 4.2.11 on 2024-05-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0003_alter_dishes_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
